# Generated by Django 5.2.7 on 2025-11-25 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gym_app", "0013_remove_chatbot_config"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="attendance",
            name="attendance_user_checkout_idx",
        ),
        migrations.RemoveIndex(
            model_name="attendance",
            name="attendance_checkin_idx",
        ),
        migrations.RemoveIndex(
            model_name="conversation",
            name="conversation_id_idx",
        ),
        migrations.RemoveIndex(
            model_name="conversation",
            name="conversation_user_updated_idx",
        ),
        migrations.RemoveIndex(
            model_name="payment",
            name="payment_user_status_date_idx",
        ),
        migrations.RemoveIndex(
            model_name="payment",
            name="payment_reference_idx",
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="user_email_idx",
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="user_kiosk_pin_idx",
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="user_name_idx",
        ),
        migrations.RemoveIndex(
            model_name="usermembership",
            name="membership_user_status_end_idx",
        ),
        migrations.RemoveIndex(
            model_name="walkinpayment",
            name="walkin_payment_date_idx",
        ),
        migrations.AddField(
            model_name="usermembership",
            name="approved_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the membership was approved by staff",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="usermembership",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
